#program for gambling using random library

#store value which user has guessed
guessNumber=input( "enter your number between 1 to 10 >")

#library imported
import random

#the number generated by computer by using randintt function of random library which chooses any random number between 1 to 10
secretNumber= random.randint(1,10)

#printing the random number generated by computer
print("secret number is {}".format(secretNumber))
    
#using if else condition for comparison of user number and computerized number
if(guessNumber==secretNumber):
    print(" player wins computer lose")

#used elif as if the inputed number will be greater than 10 it will print it as an invalid number.
elif(guessNumber>10):
    print( "{} is an invalid number".format(guessNumber))
    
else:
    print("better luck next time computer wins")
    print("secret number is {} and guessed number is {}".format(secretNumber,guessNumber))

#this is a nested situation where we have used if again in else statement as we wanted to print low or high fro the guessed number.
    if(guessNumber>secretNumber):
        print(" guessed number high than secret number")
    else:
        print("guessed number is low than secret number")

    
