#program for gambling using random library and looping it till the time you win with fixed number of trials



#library imported
import random

#the number generated by computer by using randintt function of random library which chooses any random number between 1 to 10
secretNumber= random.randint(1,10)

while(True):
    
#store value which user has guessed
    guessNumber=input( "enter your number between 1 to 10 >")

    
#using if else condition for comparison of user number and computerized number
    if(guessNumber==secretNumber):
        print(" player wins computer lose")
        break

#used elif as if the inputed number will be greater than 10 it will print it as an invalid number.
    elif(guessNumber>10):
        print( "{} is an invalid number".format(guessNumber))
    
    else:
        print("better luck next time computer wins")
        print("guessed number is {}".format(guessNumber))
        

#this is a nested situation where we have used if again in else statement as we wanted to print low or high fro the guessed number.
        if(guessNumber>secretNumber):
            print(" guessed number is high than secret number")
        else:
            print("guessed number is low than secret number")
        
        
            
    
        

    
